const Create = require('./core/Create')

console.clear()

Create().run('users', function (table) {
  table.increments('email', 10)
  table.bigIncrements('name', 30)
  table.binary('binary_nih')
  table.boolean('confirmed')
  table.char('ini_char')
  table.date('create_at')
  table.dateTime('created_at')
  table.decimal('decimal_nih')
  table.double('double_nih')
  table.enumData('enum_nih', ['0', '1', '2'])
  table.float('float_nih')
  table.integer('integer_nih')
  table.json('json_nih')
  table.jsonb('jsonb_nih')
  table.longText('longText_nih')
  table.mediumInteger('mediumInteger_nih')
  table.mediumBlob('mediumBlob_nih')
  table.mediumText('mediumText_nih')
  table.smallInteger('smallInteger_nih')
  table.tinyInteger('tinyInteger_nih')
  table.string('string_nih')
  table.text('text_nih')
  table.time('time_nih')
  table.timestamp('timestamps_nih')
})